### PR TITLE
Update dependencies to latest versions / Add Jest / Use prepare instead of prepublish

### PR DESCRIPTION
**Pull request by a-tarasyuk**
This PR includes the following changes 

1. Update all dependencies to latest versions, including `@types`
2. Add `Jest` as test runner
3. Use `enzyme` instead of `react-dom/test-utils`
4. Use `expect`*(jest assertions)* instead of `assert`
5. Fix some test cases
6. Use `prepare` instead of `prepublish`. `prepublish` **[was deprecated](https://github.com/xfiveco/generator-chisel/issues/199)** in new npm version

### CODE REVIEW

**Comment by deregtd** [comment]
Sorry for delaying here.  We've been discussing the best way to deal with the react 16 componentWillMount issue for the last few days and wanted to close on that before taking your submission.  Thanks for the patience. :)  We will check this out in the morning.

**Comment by a-tarasyuk** [comment]
@deregtd I've merged last updates here. Above I described what this PR contains. If these changes make sense, you can review them. Thanks

**Comment by deregtd** [comment]
After a quick pass on this:
* What is the advantage of changing to jest for test running?  We didn't have any complaints with mocha.
* We need to have a way to run tests through the web in test.html.  Debugging issues in Chrome is far better than printf().

**Comment by a-tarasyuk** [comment]
@deregtd 
 
> What is the advantage of changing to jest for test running? We didn't have any complaints with mocha.
> We need to have a way to run tests through the web in test.html. Debugging issues in Chrome is far better than printf().

Ok, I understood, I'll remove this PR. When I was updating dependencies, I thought that would be great to have test runner in order to avoid making every time *build* to run tests and check it in browser., *Jest* is a great tool which almost covers all cases which need to write and run tests, Mocha also it good tool, however, Jest more natural for React world. Also, `enzyme` has great API  to mount components and get/set state/props. Also, I thought that would be better to add such work to CI which will run tests, make build and publish a new version, and avoid to do it by hand. I think, to debug library we can add Webpack dev server and use it for development purposes.

**Comment by deregtd** [comment]
We can do both -- in the Skype repository, we migrated from mocha to jasmine for our unit tests, and utilize phantomjs for in-console tests through CI, and a webpack build for browser tests through a test.html file (similar structure to here.)  So, if you're just looking for a way to build the tests through CI, I think both can be accommodated.  I'm not attached to jasmine vs jest or anything -- they both look like they have similar syntax.  We just want to make sure that tests are still runnable via web as well as console.  So if you can take this structure and re-add the ability to do the web build for in-browser testing, then that's fine by us as well.

**Comment by a-tarasyuk** [comment]
@deregtd 

There is the _[**branch**](https://github.com/a-tarasyuk/ReSub/tree/feature/jasmine)_ where were added there following tools: 
- Jasmine, 
- Karma + Chrome
- Travis CI

**Pull request closed without merging**
